### ISSUE TITLE
Diğer kısmına eklenme

### ISSUE THREAD

**Issue by Reqrefusion** [h-enes-simsek/EksiEngel#1]
Eklenti oldukça güzel ancak entry'i yeni sayfada açıp kullanmak yerine entrylerin diğer kısmından kullanılmaz mı? Ayrıca saçma dakika da sadece 6 kişi engelleme olayı yüzünden eklentiyi bu şekilde yapmanız harika olmuş ancak bu yapılırken ekşide doğrudan kimseyi engelleyemiyoruz. Engelleme çalışırken doğrudan engelenenlerde bu engelleme listesi dahil olursa harika olur.

**Comment by h-enes-simsek** [comment]
Entry'nin ayarlar menüsü (üç nokta) kısmına bir ayar daha ekleyip herkesi engelleme butonu konulabilir. Eğer kastettiğiniz şey buysa çok güzel bir fikir ve todo listeme ekledim, teşekkür ederim.

Eklenti, engel işlemi sürerken aslında sizin başka bir engel yapmanıza mani olmuyor. Cooldown süresi içinde siz bir engel daha yapmaya çalıştığınız için engel işleminiz başarısız oluyor ama Ekşi Sözlük size bunu söylemiyor. Az önce test ettim cooldown süreci içinde değilken engel yapabiliyorsunuz. 

O halde Ekşi Engel çalışırken ben tek bir yazarı nasıl engelleyeceğim diye soruyorsanız Liste'den Engel özelliğini kullanın.  Diyelim ki favoriden engel özelliği ile 150 kişi engel işlemi devam ediyor. Listeden engel sayfasını açın ve istediğiniz yazarı yazıp engelleme butonuna tıklayın. Ekşi Engel isteğinizi kuyruğa alacak, favori engelinden sonra liste engelini işleyecek. Kuyruğa birden çok liste ve birden çok favori engeli ve hatta tüm engelleri kaldır işlemi alınabiliyor, bir limiti yok.

Dediklerinizi bu şekilde anladım.

**Comment by Reqrefusion** [comment]
> Entry'nin ayarlar menüsü (üç nokta) kısmına bir ayar daha ekleyip herkesi engelleme butonu konulabilir. Eğer kastettiğiniz şey buysa çok güzel bir fikir ve todo listeme ekledim, teşekkür ederim.
> 
> Eklenti, engel işlemi sürerken aslında sizin başka bir engel yapmanıza mani olmuyor. Cooldown süresi içinde siz bir engel daha yapmaya çalıştığınız için engel işleminiz başarısız oluyor ama Ekşi Sözlük size bunu söylemiyor. Az önce test ettim cooldown süreci içinde değilken engel yapabiliyorsunuz.
> 
> O halde Ekşi Engel çalışırken ben tek bir yazarı nasıl engelleyeceğim diye soruyorsanız Liste'den Engel özelliğini kullanın. Diyelim ki favoriden engel özelliği ile 150 kişi engel işlemi devam ediyor. Listeden engel sayfasını açın ve istediğiniz yazarı yazıp engelleme butonuna tıklayın. Ekşi Engel isteğinizi kuyruğa alacak, favori engelinden sonra liste engelini işleyecek. Kuyruğa birden çok liste ve birden çok favori engeli ve hatta tüm engelleri kaldır işlemi alınabiliyor, bir limiti yok.
> 
> Dediklerinizi bu şekilde anladım.

Evet üç nokta kısmı için böyle bir şey demiştim. Diğer dediğim için evet listeden engellemek mantıklı ama uygulamanın amacı bu işleri kolaylaştırmak değil mi zaten? Sınır 6 olduğu için ki eklenti bunları hemen engelliyor birini engellemek için 1 dakika bekliyoruz. Engelleme 2 saniye sürerken bekleme 60 saniye sürüyor. 150 kişiyi engellerken 25 dakika boyunca birilerini engelleyemiyorsunuz. Benim isteğim cooldown süresi içinde engellenmek istenen kişilerin otomatik olarak listeye eklenmesi.

**Comment by h-enes-simsek** [comment]
Mesela, Ekşi Engel, Ekşi Sözlük'teki engel butonlarını bypass ederek işlemleri kendi kuyruğuna alıp yapabilir bu mümkün. Bir yazarı engellemeye çalıştığınızda Ekşi Engel, popup gibi bir arayüzle bu yazarın engel kuyruğuna alındığını söyleyebilir. Ve bu da belki ayarlardan açılıp kapatılabilir bir özellik haline getirilebilir. 

Ama böyle bir şeyi ister misiniz bilmiyorum çünkü ben eklentilerin kullandığım web sayfasına doğrudan müdahale etmesinden pek hoşlanmıyorum. Ekşi Sözlük'e bir güncelleme geldiğinde web sayfasını bozabiliyor.  todo listeme ekledim, ancak daha makul bir şekilde bu problemin çözülmesi gerekiyor.

**Comment by Reqrefusion** [comment]
Fazladan seçenek göz çıkarmaz. Bu özelliği sadece favoriler engellenirken çalışması içinde ayarlanabilir. Esas sorun ekşi sözlüğün salak saçma dakikada 6 engelleme kararı. Bunu bir şekilde çözmüşsünüz ancak bu özelik eklenerek bir diğer negatif etkisini de çözebilirsiniz.

Ben isterim belki başkası istemez bilemem ancak dediğiniz gibi açılır kapanır bir özellik yapabilirsiniz. İsteyen açar isteyen açmaz yada demin dediğim gibi sadece eklenti çalışırken bu özelliğin çalışmasını da sağlayabilir ve bu salak kararın tüm negatif etkilerini yok eder. 

Ekşi sözlük değişecek. Gerçekten çok komik bir espri. Ekşi sözlükte dediğiniz özelliğin çalışmasını engelleyecek bir değişikliğin yakın zamanda olacağını hiç sanmıyorum. İşin komik yanı ben bir eklentinin sayfaya müdahale etmesine bayılıyorum. Tüm dünyada bayılıyor ki en popüler eklentiler adblockerlar. Ekşi sözlük yönetimini protesto etmek için bile adblocker kullanırdım.

**Comment by h-enes-simsek** [comment]
Eklentiyi yaklaşık bir yıl önce geliştirmeye başladım ve bu süreçte Ekşi Sözlük'teki güncellemeleri yakından takip ettim. Ekşi Sözlük'ün zannettiğinizden daha çok güncelleme aldığını düşünüyorum ama yavaş yavaş ve ufak ufak değiştiği için fark edemiyorsunuz. 

Bu issue açık kalsın, bahsi geçenlerle ilgili gelişmeleri burdan paylaşırım.

**Comment by h-enes-simsek** [comment]
V2.3 ile eklenti menüsündeki butonlar ekşi GUI'e taşındı dolayısıyla cooldown sürecinde yapılan engellemeler de kuyruğa alındığı için sorun çözüldü. Ayrıca eski ekşi sözlük butonları bypass edilmek yerine yenileri yanına eklendi, dizayn problemi ayarlara gerek kalmadan böylece çözüldü.
