### ISSUE TITLE
'Basliklarini engelle' ozelligi opsiyonel olsun

### ISSUE THREAD

**Issue by crimeofheart** [h-enes-simsek/EksiEngel#10]
Engelledigimiz veya sessize aldigimiz yazarlar bir cok konuda (mesela yeni bir film) baslik acabiliyor. Entrylerini engelledigimiz yazarin basliklarini engellemek bu yuzden eksi sozlugun faydali iceriklerine erisimi de kisitlayabiliyor. Bunun onune gecebilmek icin basligi engelleme olayini opsiyonel hale getirmeniz mumkun mu? Cok tesekkurler.

**Comment by h-enes-simsek** [comment]
Ben çok gerekli bulmamıştım ama ikinci kez aynı talebi alıyorum. Engellenen yazarın açtığı başlığı görmek aslında 'trollerle mücadele' fikrinden uzak bir istek. Bunun yanında Ekşi Sözlük, yapısı gereği trol başlıkların ve sıradan başlıkların birbirinden kolayca ayırt edilebileceği bir mecra değil. Her kullanıcı trollerle mücadele kapsamında kendi kullanıcı deneyimini olumsuz etkileyecek bir riski de tabi almak zorunda değil. Bununla birlikte belki de artık Ekşi Engel'i trollerle mücadele çabası yerine insanların işini kolaylaştıran bir araç gibi görmeyi kabul etmem lazım. Bu durumda artık ben de başlık engellemenin opsiyonel olması gerektiğini düşünüyorum. Bir sonraki versiyonda gerekli düzenlemeleri yaparım.

**Comment by h-enes-simsek** [comment]
v3.0 ile ayarlar menüsünden kapatılabiliyor.
