### ISSUE TITLE
Entry menusunde opsiyonlar cikmiyor

### ISSUE THREAD

**Issue by crimeofheart** [h-enes-simsek/EksiEngel#3]
Entryinin menusunde eklentinin opsiyonlari bende gorunmuiyor. Baslik tasitma hakkim oldugu icin olabilir mi emin degilim ama bende cikan opsiyonlar eklentinin sayfasindaki ekran goruntusunden farkli.  Kullanici menusunde bir sikinti yok.
[Ekran goruntusu](https://imgur.com/a/U6cn4XL)

**Comment by h-enes-simsek** [comment]
Evet muhtemelen başlık taşıma ile ilgili, sizdeki frontend kodları biraz farklıydı ve bundan dolayı çalışmıyordu. Gerekli düzenlemeleri yaptım, uzaktan test etmek mümkün değil ama v2.4 ile sorunun çözülmesi gerekiyor. Yakında güncelleme yayınlanır.
