### ISSUE TITLE
takipçilerini engelle

### ISSUE THREAD

**Issue by Spica-Suzuki** [h-enes-simsek/EksiEngel#6]
yazarların (trollerin) takipçilerini profillerindeki üç noktadan da engelleme özelliği getirilebilir (bkz: medya). Bunun yanı sıra aynı anda hem başlık hem de kişi engelleme veya trollün takipçilerinin her biri için başlık da engelleme özelliği yapılıyorsa yapılabilir. Detaylara çok hakim değilim, sadece görüşümü paylaşmak istedim belki olur diye.
 
![image](https://user-images.githubusercontent.com/76227757/233225443-047965a4-0284-41bf-9f28-a731bb7a4a41.png)

**Comment by h-enes-simsek** [comment]
Merhaba, yazar profiline takipçilerini engelle özelliği gelmesi gerekiyor, şu an yapılacaklar listemde. diğer isteğinizi anlayamadım. zaten herhangi bir engel işlemi (engelle veya sessize al) + başlıklarını engelle şeklinde gerçekleşiyor. engelle veya sessize al seçeneği ise ayarlarda mevcut.

**Comment by h-enes-simsek** [comment]
v2.6 ile yazarların profil sayfalarına takipçilerini engelle butonu eklendi.
