### ISSUE TITLE
engellilerin engellenmesi

### ISSUE THREAD

**Issue by Spica-Suzuki** [h-enes-simsek/EksiEngel#7]
Yazarın takipçileri engellendiği zaman bir daha engelleme seçeneği seçilirse tekrardan engellemeye çalışıyor.

Yani bir trollün 200 tane troll takipçisini engellemişsem başka bir trollün de 200 takipçisini engellerken bu takipçielirn ortak kümenin elemanları olma olasılığı var. Dakikada 6 tane engel sınırı olan  bir platform için oldukça zaman kaybına dönüşebiliyor bu durum. Eğer yapılabiliyorsa daha önce engel atılan insanlar, yeni engellenen insanların arasında bulunmamalı. Böylece daha hızlı ve verimli bir şekilde engel atılabilir.

**Comment by h-enes-simsek** [comment]
gayet güzel bir fikir ve uzun zamandır aklımda ancak üşeniyordum. birisi farketmesin diye her gece dua ettim ama artık zamanı geldi galiba :smile:

**Comment by h-enes-simsek** [comment]
v2.6 ile gerçeklendi. ayarlardan açılıp kapatılabiliyor.
