### ISSUE TITLE
eksisozluk1923.com

### ISSUE THREAD

**Issue by Reqrefusion** [h-enes-simsek/EksiEngel#8]
Eklenti eski siteye göre ayarlı olduğu için yeni sitede görülmüyor. Bu sorunu bayağı yaşayacağız. İçinde eksisozluk kelimesi içerip içermemesine göre çalışması daha iyi olur.

**Comment by h-enes-simsek** [comment]
Merhaba, bu mümkün değil çünkü isteklerin bir IP adresine gitmesi gerekiyor. Muhtemelen sorunu birkaç gün içinde şöyle çözeceğim. Kullanıcılar, Ekşi Engel sunucusuna en yeni Ekşi Sözlük'ün hangi adreste olduğunu soracak ve istekleri bu adrese gönderecek. Eklentinin Ekşi Engel'e bağımlı olması hoş değil ama şu an için yapacak fazla bir şey yok gibi. 

Issue'lar ile katkı sağladığınız için çok teşekkür ederim. 😃

**Comment by Reqrefusion** [comment]
Durum:
İşlem başlayacak.
Cooldown:
?
Başarılı işlem:
0
Gerçekleşen işlem:
0
Planlanan işlem:
0
Yeni güncellemeyle görünüyor ancak her özellik kullanımında bu şekilde takılıyor.

**Comment by h-enes-simsek** [comment]
İki bilgisayarda denedim çalışıyor görünüyor. Ayrıca gelen loglar en azından bazı başka kişilerde çalıştığını gösteriyor. İncelemek için bana logları gönderirseniz sevinirim, bakalım sorun neymiş.

- Google chrome'da şu adrese gidin: chrome://extensions/
- Sağ üstte Developer mode seçeneğini açın
- Ekşi Engel'in olduğu kısımda bir link var, ingilizce adı 'service worker' veya 'service worker (Inactive)' olmalı. Bu linke tıklayın, geliştirici konsolu açılacak.
- Konsol açıldığında eğer farklı sekmedeyse 'Console' sekmesine gelin.
- Konsol açıkken Ekşi Engeli kullanın, mesela bir entry'i favorileyenleri engelle butonuna tıklayın.
- Biraz bekleyin, konsola akan loglar durduğunda kopyalayıp buraya yapıştırın. Loglar içinde ekşi kullanıcı adınız hariç kişisel bir veri yok. İsterseniz yapıştırmadan önce kullanıcı adınızı aratıp silersiniz.

Belki sonraki versiyonlarda logları kolayca almak için bir arayüz tasarlanabilir.

**Comment by Reqrefusion** [comment]
```
INFO 2023_5_23_13_29_24_306 bg: init.
log.js:64 INFO 2023_5_23_13_30_16_822 bg: a new process added to the queue, banSource: FAV, banMode: BAN
log.js:64 INFO 2023_5_23_13_30_16_825 Process has been started with banSource: FAV, banMode: BAN, entryUrl: xxx, singleAuthorName: nevonevo, singleAuthorId: 1788785
log.js:64 INFO 2023_5_23_13_30_16_826 bg: number of waiting processes in the queue: 0
log.js:64 INFO 2023_5_23_13_30_16_826 bg: (update_Planned in messageListener_Popup) notification page's queue will be updated.
log.js:64 INFO 2023_5_23_13_30_16_864 bg: (update_Planned in processHandler) notification page's queue will be updated.
log.js:64 ERR 2023_5_23_13_30_16_870 bg: (update_Planned in popopListener) could not establish a connection with notification page
log.js:64 INFO 2023_5_23_13_30_16_873 Config restored from storage
log.js:64 ERR 2023_5_23_13_30_16_908 bg: (update_Planned in processHandler) could not establish a connection with notification page
log.js:64 INFO 2023_5_23_13_30_17_375 is EksiSozluk accessible: true at https://eksisozluk1923.com
log.js:64 INFO 2023_5_23_13_30_17_971 scrapingHandler: clientName: xxxx
log.js:64 INFO 2023_5_23_13_30_18_617 number of user to ban (before analysis): 1
```
Bu şekilde

**Comment by h-enes-simsek** [comment]
Yani bir hata vermiyor gibi. 'Takip ettiğim yazarları engelleme' ve 'Sadece gerekli işlemleri yap' ayarları açıksa ki default olarak açık, bu işlemler için takip edilen yazarların ve engelli yazarların okunması gerekiyor. Eğer çok fazla kişi engellediyseniz veya çok fazla yazar takip ediyorsanız belki bu adım sizde çok uzun sürüyordur. Belki de bir hata durumu oluşuyor ama eklenti, yakalayamıyor.

Bahsettiğim iki ayarı kapatıp tekrar deneyebilir misiniz?

**Comment by h-enes-simsek** [comment]
v2.6 ile Ekşi Sözlük'teki domain değişliklerine daha hızlı müdahale edebilmek için gerekli mekanizma tamamlandı. Ekşi Engel sunucularında barındırılan bir API ile artık Ekşi Sözlük'ün son geçerli adresi alınabiliyor. Ekşi Engel eklentisi ise artık kendi kaynak kodlarına gömülü URL çalışmazsa API üzerinden Ekşi Sözlük'ün son adresine erişip çalışmaya devam ediyor. Domain değişikliği yaşandığında artık Ekşi Engel'i güncellememe gerek kalmadı, sadece API'ın değişmesi yeter. 

Bahsettiğiniz soruna cevap vermediğiniz ve bu issue da domain değişiklikleri olduğu için issue'yu kapatıyorum.

**Comment by Reqrefusion** [comment]
Ayarları değiştirince sorun çözüldü teşekkürler.

**Comment by angelfire76** [comment]
@h-enes-simsek 
Maalesef yeni adres olarak yine 1923'ü alıp bağlanmaya çalışıyor.

INFO 2023_12_22_16_1_52_342 is EksiSozluk accessible: false at https://eksisozluk1923.com
WARN 2023_12_22_16_1_52_342 EksiSozluk is not accessible at: https://eksisozluk1923.com
INFO 2023_12_22_16_1_52_996 Obtained EksiSozluk URL: https://eksisozluk1923.com
ERR 2023_12_22_16_1_52_996 Obtained EksiSozluk URL is the same with the one in the config
ERR 2023_12_22_16_1_52_996 Program has been finished (finishErrorAccess)
incoming message: FINISH

Bildirim ekranında da "Durum: Ekşi Sözlük'e erişilemedi." diyor.

**Comment by h-enes-simsek** [comment]
> @h-enes-simsek Maalesef yeni adres olarak yine 1923'ü alıp bağlanmaya çalışıyor.
> 
> INFO 2023_12_22_16_1_52_342 is EksiSozluk accessible: false at https://eksisozluk1923.com WARN 2023_12_22_16_1_52_342 EksiSozluk is not accessible at: https://eksisozluk1923.com INFO 2023_12_22_16_1_52_996 Obtained EksiSozluk URL: https://eksisozluk1923.com ERR 2023_12_22_16_1_52_996 Obtained EksiSozluk URL is the same with the one in the config ERR 2023_12_22_16_1_52_996 Program has been finished (finishErrorAccess) incoming message: FINISH
> 
> Bildirim ekranında da "Durum: Ekşi Sözlük'e erişilemedi." diyor.

Yeni adres sorunu çözüldü. Haber verdiğiniz için teşekkürler.
