### ISSUE TITLE
Toast ile Bildirim 

### ISSUE THREAD

**Issue by Reqrefusion** [h-enes-simsek/EksiEngel#9]
Engel'e basılınca yeni sekmede süreç işliyor ancak hala okumaya devam ederken ve engelleme yaparken sadece kuyruğa ekliyor ve geri bildirim vermiyor. Ekşi'nin mevcut toast sistemi gibi ama sağ alt köşede bildirimde bulunulursa çok iyi olur. Daha iyi geri bildirim alınır.

**Comment by h-enes-simsek** [comment]
v2.7 ile butonlara geri bildirim eklendi. Ekşi Sözlük'ün orijinal toaster'ı ufak bir değişiklikle kullanıldı.
